name: Auto PR Description

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - stage

jobs:
  auto_pr_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --all

      - name: Get commit messages from master to current branch
        id: get_commits
        run: |
          commits=$(git log --pretty=format:"- %s" origin/master..HEAD)
          echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
          echo "$commits" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR description
        uses: actions/github-script@v7
        env:
          COMMIT_MESSAGES: ${{ env.COMMIT_MESSAGES }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitMessages = process.env.COMMIT_MESSAGES;
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const newBody = `### Commit Messages:\n${commitMessages}\n\n${pr.body || ''}`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: newBody
            });
